language: cpp
dist: xenial

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - python3-pip
      - python3-setuptools
      - ninja-build
      - gcc-7

install:
  # The meson included in the Xenial repositories is too old (0.29).
  - pip3 install meson
  - export CC=gcc-7

script:
  - mkdir build
  - meson build
  - ninja -v -C build
  - meson test -v -C build
