name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Environment
      run: echo "::add-path::$HOME/.local/bin"
    - name: Install dependencies
      run: |
        sudo apt install -y python3-setuptools ninja-build
        pip3 install meson
    - name: Configure
      run: mkdir build; meson -Dbuildtype=debugoptimized build
    - name: Build
      run: ninja -v -C build
    - name: Test
      run: meson test -v -C build
